# Generated by Django 5.2.17 on 2026-09-07 23:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('BABY', 'Baby fútbol'), ('F7', 'Fútbol 7'), ('F11', 'Fútbol 11')], default='F7', max_length=4, verbose_name='tipo')),
                ('superficie', models.CharField(blank=True, max_length=60, verbose_name='superficie')),
                ('precio_hora', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='precio por hora (CLP)')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'cancha',
                'verbose_name_plural': 'canchas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10, verbose_name='rol')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('bloqueado', models.BooleanField(default=False, help_text='Se activa solo al acumular 10 faltas vigentes (RN-05).', verbose_name='bloqueado')),
                ('bloqueado_en', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado el')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='inicio del bloque')),
                ('fin', models.DateTimeField(verbose_name='fin del bloque')),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_PAGO', max_length=20, verbose_name='estado')),
                ('precio', models.PositiveIntegerField(verbose_name='precio cobrado (CLP)')),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicitada el')),
                ('vence_en', models.DateTimeField(help_text='RN-02: min(solicitada + 30 min, inicio del bloque).', verbose_name='vence el')),
                ('pagada_en', models.DateTimeField(blank=True, null=True, verbose_name='pagada el')),
                ('vencida_en', models.DateTimeField(blank=True, null=True, verbose_name='vencida el')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cancha', verbose_name='cancha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('confirmada_por', models.ForeignKey(blank=True, help_text='RN-03: qué administrador validó el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='pago confirmado por')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200, verbose_name='motivo')),
                ('registrada_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrada el')),
                ('vigente', models.BooleanField(default=True, help_text='Solo las faltas vigentes cuentan para el bloqueo (RN-05).', verbose_name='vigente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='falta', to='reservas.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'falta',
                'verbose_name_plural': 'faltas',
                'ordering': ['-registrada_en'],
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cancha', 'inicio'], name='reservas_re_cancha__8cf34a_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado', 'vence_en'], name='reservas_re_estado_8494a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='reserva_fin_posterior_al_inicio'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE_PAGO', 'PAGADA'])), fields=('cancha', 'inicio'), name='una_reserva_vigente_por_cancha_y_bloque'),
        ),
        migrations.AddIndex(
            model_name='falta',
            index=models.Index(fields=['cliente', 'vigente'], name='reservas_fa_cliente_924154_idx'),
        ),
    ]
